AWSTemplateFormatVersion: "2010-09-09"
Transform: AWS::Serverless-2016-10-31
Resources:
    LambdaFunc:
      Type: AWS::Serverless::Function
      Properties:
          CodeUri: .
          Runtime: python3.13
          Handler: calc.handler
          Timeout: 30